### ISSUE TITLE
Improvement* Searching elements by their atomic number.

### ISSUE THREAD

**Issue by Jalaj1087** [Lucas256-cmd/Flow.Launcher.Plugin.PeriodicTable#4]
I find this plugin very useful. But a small improvement would be the able to search using the Atomic number of the element.

Ex. 'pt 1' would give the result for 'Hydrogen'.

**Comment by Lucas256-cmd** [comment]
Wow, I never thought anyone would use this plugin except for me, I'm really glad you like it. As for your suggestion, I will look to add this feature and I'll keep you updated.

**Comment by Lucas256-cmd** [comment]
See my comment here: https://github.com/asmpro7/ElementFlow/issues/1#issuecomment-256148311
I think that plugin has more merit than mine so I fixed that one, I think.

**Comment by Jalaj1087** [comment]
Actually I really wanted the feature of periodic table into Flow but never that plugin didn't work. So the Elementflow plugin is fixed now I think? Anyways I loved to use this plugin. Hope you make more good codes for the community.

**Comment by Lucas256-cmd** [comment]
If everything went well, I fixed Element-flow so you should get and update soon, sometimes it can take a while for the update to become available in the plugin store. So you have a periodic table plugin in flow now.

 In my opinion ElementFlow is a better plugin because it gives way more information. So when you have some extra request, you could also ask it there, maybe someone else or me can improve that plugin some more if necessary (I'm not that good of a programmer but I can always try). 

Or do you like my plugin (PeriodicTable) more? I could also add the feature you asked. It's just that Element-flow has a better base than mine, there are more features already supported.

**Comment by Jalaj1087** [comment]
Yeah, element flow is providing more information. Much thanks for fixing that plugin. It would be better for if the community gets new plugins giving more usability to the program.
